### ISSUE TITLE
Support plugins explicitly loaded at runtime

### ISSUE THREAD

**Issue by frutiger** [frutiger/bdemeta#12]
A plugin explicitly loaded at runtime is a dynamically loadable module that exports some set of symbols.  Other code may then load and use those symbols using operating system provided facilities (e.g. `dlopen` or `LoadLibrary`) if it knows the names and types of the exported symbols.

These dynamically loadable modules would have to be deployed together with the code using them in order to avoid mismatched symbol names and symbol signatures/behaviours.

This would implement option (1) from #7.

**Comment by frutiger** [comment]
I believe this is supported on the `plugins` branch (at 0a7237d404b8a217b2b24bdecee5c1cc5ceb535e).  @cppguru, please let me know if that branch provides support for this kind of plugin, thanks!

**Comment by cppguru** [comment]
I think the support was not fully there, because it was not possible to
depend on what's inside a plugin without getting it into the link line.  I
may remember wrong.

**Comment by frutiger** [comment]
Ah yes, you are right, that support is still not there, however it should be relatively simple to add, I'll see what I can do.

**Comment by cppguru** [comment]
Thanks!

**Comment by frutiger** [comment]
It's possible that ce6613fa134dd8645626803f36a0e7d75e4b9a0f fixes this issue.  The tests would indicate so, but I have yet to actually build something with it!

**Comment by frutiger** [comment]
It is currently considered out of scope for `bdemeta` to support understanding dependencies between libraries at runtime.  Note that code may load a dependency at runtime as usual, there is no magic provided by the build system to automatically switch between a library loaded at runtime vs. linked against at link time.
